# Generated by Django 5.2.13 on 2026-05-03 20:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="bloodreport",
            name="ai_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="bloodreport",
            name="file_type",
            field=models.CharField(
                choices=[("PDF", "PDF"), ("IMAGE", "Image")],
                default="PDF",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="is_accepting_appointments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="medical_license_no",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("PATIENT", "Patient"),
                ],
                default="PATIENT",
                max_length=20,
            ),
        ),
    ]
