# Generated by Django 5.2.13 on 2026-05-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_bloodreport_ai_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_service_account_json', models.TextField(blank=True, help_text='Paste the full JSON key of your Google Cloud service account here. This is used to authenticate Drive API calls.')),
                ('google_drive_root_folder_id', models.CharField(default='1-0RxsA0L1-0Qcp4qLYzBq5wyI2qauEjT', help_text="The root Google Drive folder ID that contains the 'Patient blood reports' and 'Patient health reports' sub-folders.", max_length=255)),
                ('n8n_blood_report_webhook_url', models.URLField(blank=True, help_text='Full URL of the n8n webhook that receives new blood report notifications.')),
                ('n8n_webhook_secret', models.CharField(blank=True, help_text="Shared secret sent as 'Authorization: Bearer <secret>' when calling n8n.", max_length=255)),
                ('n8n_callback_token', models.CharField(blank=True, help_text='Token that Django expects when n8n POSTs back the health report result.', max_length=255)),
                ('jwt_access_token_lifetime_minutes', models.PositiveIntegerField(default=60, help_text='Access token lifetime in minutes. Applied at runtime via SIMPLE_JWT setting.')),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configuration',
            },
        ),
        migrations.AddField(
            model_name='bloodreport',
            name='drive_folder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bloodreport',
            name='n8n_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_reports', to='app.patientprofile'),
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_link', models.URLField()),
                ('original_filename', models.CharField(max_length=255)),
                ('ai_summary', models.JSONField(blank=True, default=dict)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_report', to='app.bloodreport')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='app.patientprofile')),
            ],
        ),
    ]
