# Generated by Django 5.2 — patched to backfill appointment_id before adding UNIQUE constraint

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_appointment_ids(apps, schema_editor):
    """Assign APT-YYYY-NNNNNN to all existing appointments that have no appointment_id."""
    Appointment = apps.get_model("app", "Appointment")
    year = timezone.now().year
    for appt in Appointment.objects.all().order_by("id"):
        if not appt.appointment_id:
            appt.appointment_id = f"APT-{year}-{appt.pk:06d}"
            appt.save(update_fields=["appointment_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_integrationconfig_healthreport_bloodreport_n8n'),
    ]

    operations = [
        # Step 1: Add as non-unique, nullable first so existing rows get blank safely
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=25, default=''),
            preserve_default=False,
        ),
        # Step 2: Backfill existing rows before adding the UNIQUE constraint
        migrations.RunPython(backfill_appointment_ids, migrations.RunPython.noop),
        # Step 3: Now make it unique + indexed
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, db_index=True, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.appointment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, help_text='Admin notes about this token.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Token',
                'verbose_name_plural': 'User API Tokens',
            },
        ),
    ]
