# Generated by Django 5.2.13 on 2026-05-12 06:34

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_appointment_id_reportcomment_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_remarks',
            field=models.TextField(blank=True, default='', help_text="Doctor's review notes / remarks on this appointment."),
        ),
        migrations.AddField(
            model_name='bloodreport',
            name='report_file',
            field=models.FileField(blank=True, help_text='Uploaded PDF/image file stored on server.', null=True, upload_to=app.models.blood_report_upload_path),
        ),
        migrations.AlterField(
            model_name='bloodreport',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_reports', to='app.appointment'),
        ),
        migrations.AlterField(
            model_name='bloodreport',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bloodreport',
            name='drive_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
