# Generated by Django 6.1.1 on 2026-09-27 11:16

import django.db.models.deletion
from django.core.files.storage import default_storage
from django.db import migrations, models


def backfill_blobs(apps, schema_editor):
    BloodReport = apps.get_model("app", "BloodReport")
    BloodReportBlob = apps.get_model("app", "BloodReportBlob")
    for report in BloodReport.objects.exclude(report_file="").exclude(report_file__isnull=True).iterator():
        try:
            with default_storage.open(report.report_file.name, "rb") as fh:
                data = fh.read()
        except OSError:
            continue
        BloodReportBlob.objects.get_or_create(blood_report=report, defaults={"data": data})


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_bloodreport_file_appointment_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReportBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blob', to='app.bloodreport')),
            ],
        ),
        migrations.RunPython(backfill_blobs, migrations.RunPython.noop),
    ]
